### ISSUE TITLE
Suggestion: stand alone library

### ISSUE THREAD

**Issue by codeliner** [mtymek/expressive-config-manager#4]
Why **expressive** in the package name and the namespace `Zend\Expressive`?

Your ConfigManager would be a great stand alone library that can be used in different contexts not only zend-expressive (like you've stated in the readme).

**Comment by mtymek** [comment]
@codeliner I named it like this because I plan to move this library into Zend Framework organization (see initial discussion here: https://github.com/zendframework/zend-expressive-skeleton/pull/26).
Then, after initial work was done, I realized that it can be useful for different applications - that's why I put that statement in the readme file. Having `Zend\Expressive` in the namespace doesn't prevent you from using it anywhere you want - same as with `Symfony\Process` or `Zend\ServiceManager`.

I don't mind giving it a different name. It is still fresh project - let's see how it will evolve in next few weeks, and then I'll think what name makes best sense.

**Comment by codeliner** [comment]
yeah, of course I can install it stand alone. That is not the problem. I just wanted to say that it is a very good library of its own. Integrating it in expressive would mean I have to install expressive to use your ConfigManager. But when I want to write a CLI app I don't need expressive but maybe your library.
`Zend\ConfigManager` would be ok, but `Zend\Expressive\...` indicates that you want to include it in expressive. However, was just a suggestion. I'll try your lib. Want to see how well it can play together with interop-config which we use at prooph to provide framework agnostic configuration and service factories. Your config manager could be a nice addition.

**Comment by mtymek** [comment]
Happy to hear that you like it!

Sure, `Zend\ConfigManager` sounds nice. I was thinking about it as well, but Zend already has `Zend\Config`, so it may confuse some people. Anyway, I will get back to this discussion later.
